# Generated by Django 3.0.5 on 2020-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='lnk_full_name',
            field=models.CharField(db_column='lnk_full_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='links',
            name='lnk_short_name',
            field=models.CharField(db_column='lnk_short_name', max_length=16),
        ),
    ]
